name: release image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t student-list-api ./simple_api
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'student-list-api'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        run: |
          docker tag  student-list-api ${{ secrets.DOCKERHUB_USERNAME }}/student-list-api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-list-api

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: user/app:latest